intellica-tech/reporting-tool

- LICENSE.txt
> First commit

- LICENSE.txt
> second committ

- LICENSE.txt
> deneme oguzhan

- superset-frontend/src/components/DvtTitleTotal/dvt-title-total.module.tsx
- superset-frontend/src/components/DvtTitleTotal/dvt-title-total.stories.tsx
- superset-frontend/src/components/DvtTitleTotal/index.tsx
New dvt-component created name with dvt-title-total
> feat: dvt-title-total added

- superset-frontend/src/components/DvtPagination/dvt-pagination.module.tsx
- superset-frontend/src/components/DvtPagination/dvt-pagination.stories.tsx
- superset-frontend/src/components/DvtPagination/index.tsx
> feat: pagination added

- superset-frontend/packages/superset-ui-core/src/style/index.tsx
> fix: superset-ui-core in new add theme dvt fixed

- superset-frontend/src/components/DvtPagination/dvt-pagination.module.tsx
- superset-frontend/src/components/DvtPagination/dvt-pagination.stories.tsx
- superset-frontend/src/components/DvtPagination/index.tsx
- superset-frontend/src/components/DvtTitlePlus/dvt-title-plus.module.tsx
- superset-frontend/src/components/DvtTitlePlus/dvt-title-plus.stories.tsx
- superset-frontend/src/components/DvtTitlePlus/index.tsx
- superset-frontend/src/components/DvtTitleTotal/dvt-title-total.module.tsx
- superset-frontend/src/components/DvtTitleTotal/dvt-title-total.stories.tsx
- superset-frontend/src/components/DvtTitleTotal/index.tsx
> feat: 4 new component add fixed

- superset-frontend/src/components/DvtMiniNavigation/dvt-mini-navigation.module.tsx
- superset-frontend/src/components/DvtMiniNavigation/dvt-mini-navigation.stories.tsx
- superset-frontend/src/components/DvtMiniNavigation/index.tsx
New dvt-mini navigation component is added
> feat: new mini navigation component added

- superset-frontend/src/components/DvtInput/dvt-input.module.tsx
- superset-frontend/src/components/DvtInput/dvt-input.stories.tsx
- superset-frontend/src/components/DvtInput/index.tsx
> feat: dvt-input

- superset-frontend/src/components/DvtNavigation/dvt-navigation.module.tsx
- superset-frontend/src/components/DvtNavigation/dvt-navigation.stories.tsx
- superset-frontend/src/components/DvtNavigation/index.tsx
New UI component dvt-navigation is added
> feat: new ui component navigation added

- superset-frontend/packages/superset-ui-core/src/style/index.tsx
- superset-frontend/src/components/DvtDotTitle/dvt-dot-title.module.tsx
- superset-frontend/src/components/DvtDotTitle/dvt-dot-title.stories.tsx
- superset-frontend/src/components/DvtDotTitle/index.tsx
> feat: dvt-dot-title

- superset-frontend/src/components/DvtInput/dvt-input.module.tsx
> fix: dvt input password

- superset-frontend/src/components/DvtCalendar/dvt-calendar.module.tsx
- superset-frontend/src/components/DvtCalendar/dvt-calendar.stories.tsx
- superset-frontend/src/components/DvtCalendar/index.tsx
- superset-frontend/src/pages/DvtHome/index.tsx
> fix: update/dvt-caledar

- superset-frontend/src/components/DvtTitleCardList/dvt-title-card-list.module.tsx
- superset-frontend/src/components/DvtTitleCardList/dvt-title-card-list.stories.tsx
- superset-frontend/src/components/DvtTitleCardList/index.tsx
Started and Completed feat/dvt-title-card-list
> feat: started and completed feat/dvt-title-card-list

- superset-frontend/src/components/DvtProfileInformation/dvt-profile-information.module.tsx
- superset-frontend/src/components/DvtProfileInformation/dvt-profile-information.stories.tsx
- superset-frontend/src/components/DvtProfileInformation/index.tsx
> feat: DvtProfileInformatio Completed

- superset-frontend/src/assets/images/icons/dvt-star.svg
Added star icon as a svg file at feat/dvt-svg-add
> feat: added star icon as svg a file at feat/dvt-svg-add

- superset-frontend/src/components/DvtProfileMenu/dvt-profile-menu.module.tsx
- superset-frontend/src/components/DvtProfileMenu/dvt-profile-menu.stories.tsx
- superset-frontend/src/components/DvtProfileMenu/index.tsx
Started and comleted 'Profile Menu' at feat/dvt-profile-menu
> feat: started and completed feat/dvt-profile-menu

- superset-frontend/src/components/DvtList/dvt-list.module.tsx
- superset-frontend/src/components/DvtList/dvt-list.stories.tsx
- superset-frontend/src/components/DvtList/index.tsx
> feat: started and completed feat/dvt-list

- superset-frontend/src/assets/images/icons/dvt-alert2.svg
- superset-frontend/src/assets/images/icons/dvt-delete.svg
- superset-frontend/src/assets/images/icons/dvt-export2.svg
- superset-frontend/src/assets/images/icons/dvt-file.svg
- superset-frontend/src/assets/images/icons/dvt-folder.svg
- superset-frontend/src/assets/images/icons/dvt-heart.svg
> feat: added .svg files fix/dvt-svg-add

- superset-frontend/src/components/DvtTable/dvt-table.module.tsx
- superset-frontend/src/components/DvtTable/dvt-table.stories.tsx
- superset-frontend/src/components/DvtTable/index.tsx
> fix: dvt-table-checkbox

- superset-frontend/src/components/DvtButton/dvt-button.module.tsx
- superset-frontend/src/components/DvtButton/dvt-button.stories.tsx
- superset-frontend/src/components/DvtButton/index.tsx
> feat: fixed and updated button props fix/dvt-button-props-update

- superset-frontend/src/components/DvtNavigationBar/dvt-navigation-bar.module.tsx
dvt-navigation-bar width and margin-bottom deleted
> fix: dvt-navigation-bar

- superset-frontend/src/components/DvtDatepicker/dvt-datepicker.module.tsx
> fix: z-index added

- superset-frontend/src/components/DvtPopper/dvt-popper.module.tsx
- superset-frontend/src/components/DvtPopper/dvt-popper.stories.tsx
- superset-frontend/src/components/DvtPopper/index.tsx
> feat: DvtPopper

- superset-frontend/src/components/DvtNavbar/dvt-navbar-tabs-data.ts
- superset-frontend/src/components/DvtNavbar/dvt-navbar.module.tsx
- superset-frontend/src/components/DvtNavbar/index.tsx
navbar pathname güncelledim pathname lere göre gelecek olan navbar yazdım css kodlarını değiştirdim
> fix: dvt-navbar

- superset-frontend/src/components/DvtPopper/dvt-popper.module.tsx
> fix: dvt-popper

- superset-frontend/src/components/DvtTable/dvt-table.module.tsx
- superset-frontend/src/components/DvtTable/dvt-table.stories.tsx
- superset-frontend/src/components/DvtTable/index.tsx
props updated and icon style updated
> fix: dvt table

- superset-frontend/src/components/DvtSidebar/dvtSidebarData.ts
- superset-frontend/src/components/DvtSidebar/index.tsx
- superset-frontend/src/dvt-redux/dvt-sidebarReducer.ts
- superset-frontend/src/pages/DvtReports/dvt-reports.module.tsx
- superset-frontend/src/pages/DvtReports/index.tsx
- superset-frontend/src/views/dvt-routes.tsx
- superset-frontend/src/views/dvt-store.ts
> feat: dvt-reports

- superset-frontend/src/components/DvtSidebar/dvtSidebarData.ts
- superset-frontend/src/pages/DvtReports/index.tsx
> fix: Dvt-74

- superset-frontend/src/components/DvtTextarea/dvt-textarea.module.tsx
- superset-frontend/src/components/DvtTextarea/dvt-textarea.stories.tsx
- superset-frontend/src/components/DvtTextarea/index.tsx
> feat: DVT-77

- superset-frontend/src/components/DvtInput/dvt-input.module.tsx
- superset-frontend/src/components/DvtInput/dvt-input.stories.tsx
- superset-frontend/src/components/DvtInput/index.tsx
> feat: DVT-76

- superset-frontend/src/components/DvtSelect/dvt-select.module.tsx
- superset-frontend/src/components/DvtSelect/index.tsx
dvt-select selected value color added
> feat: Dvt-82

- superset-frontend/src/components/DvtNavigation/dvt-navigation.module.tsx
- superset-frontend/src/components/DvtNavigation/index.tsx
- superset-frontend/src/views/dvt-layout.tsx
> fix: DVT-84

- superset/dvt_initialization/__init__.py
- superset/views/dvt_sqllab.py
> feat: DVT-83

- superset/templates/superset/login.html
Remove non functional pieces in login page
> fix: Remove non functional pieces in login page

- superset-frontend/src/components/DvtDropdown/dvt-dropdown.module.tsx
- superset-frontend/src/components/DvtDropdown/dvt-dropdown.stories.tsx
- superset-frontend/src/components/DvtDropdown/index.tsx
> feat: DvtDropdown

- superset-frontend/src/components/DvtSelect/dvt-select.module.tsx
- superset-frontend/src/components/DvtSelect/dvt-select.stories.tsx
- superset-frontend/src/components/DvtSelect/index.tsx
> feat: DVT-95

- superset-frontend/src/components/DvtCollapse/dvt-collapse.module.tsx
- superset-frontend/src/components/DvtCollapse/dvt-collapse.stories.tsx
- superset-frontend/src/components/DvtCollapse/index.tsx
> feat: DVT-93

- superset-frontend/src/components/DvtDragCard/dvt-drag-card.module.tsx
- superset-frontend/src/components/DvtDragCard/dvt-drag-card.stories.tsx
- superset-frontend/src/components/DvtDragCard/index.tsx
> feat: DVT-97

- superset-frontend/src/components/DvtNavbar/index.tsx
- superset-frontend/src/components/DvtSidebar/dvtSidebarData.ts
- superset-frontend/src/components/DvtSidebar/index.tsx
- superset-frontend/src/dvt-redux/dvt-navbarReducer.ts
- superset-frontend/src/pages/DvtSql/dvt-sql.module.tsx
- superset-frontend/src/pages/DvtSql/index.tsx
- superset-frontend/src/views/dvt-routes.tsx
- superset-frontend/src/views/dvt-store.ts
> feat: Dvt62/sql page

- superset-frontend/src/components/DvtPopper/dvt-popper.module.tsx
- superset-frontend/src/components/DvtPopper/dvt-popper.stories.tsx
- superset-frontend/src/components/DvtPopper/index.tsx
> feat: fixed and updated popover dvt99/popover-sizing

- superset/dvt_initialization/__init__.py
> fix: Filterset fix

- superset-frontend/src/components/DvtDragCard/dvt-drag-card.module.tsx
- superset-frontend/src/components/DvtDragCard/dvt-drag-card.stories.tsx
- superset-frontend/src/components/DvtDragCard/index.tsx
> fix: DvtDragCard

- superset-frontend/src/components/DvtInputDrop/dvt-input-drop.module.tsx
- superset-frontend/src/components/DvtInputDrop/dvt-input-drop.stories.tsx
- superset-frontend/src/components/DvtInputDrop/index.tsx
> feat: DVT-98

- superset-frontend/src/components/DvtDragCardList/dvt-drag-card-list.module.tsx
- superset-frontend/src/components/DvtDragCardList/dvt-drag-card-list.stories.tsx
- superset-frontend/src/components/DvtDragCardList/index.tsx
> fix: DVT-100

- superset-frontend/src/components/DvtNavbar/index.tsx
- superset-frontend/src/components/DvtSidebar/index.tsx
> feat: commented welcome page dvt89/welcome-page-comment-out

- superset-frontend/src/components/DvtInput/dvt-input.module.tsx
- superset-frontend/src/components/DvtInput/dvt-input.stories.tsx
- superset-frontend/src/components/DvtInput/index.tsx
> feat: DVT-94

- superset-frontend/src/components/DvtNavbar/index.tsx
- superset/dvt_initialization/__init__.py
> fix: remove unused imports

- superset/config.py
- superset/dvt_config.py
- superset/dvt_initialization/__init__.py
- superset/translations/tr/LC_MESSAGES/messages.json
- superset/translations/tr/LC_MESSAGES/messages.po
> feat: turkish language support

- superset-frontend/src/components/DvtCard/dvt-card.stories.tsx
- superset-frontend/src/components/DvtCard/index.tsx
- superset-frontend/src/components/DvtDropdown/dvt-dropdown.module.tsx
- superset-frontend/src/components/DvtDropdown/index.tsx
- superset-frontend/src/components/DvtTitleCardList/dvt-title-card-list.stories.tsx
- superset-frontend/src/components/DvtTitleCardList/index.tsx
- superset-frontend/src/pages/DvtHome/index.tsx
Dropdowns on cards have been updated dvt101/update-cards.
> feat: Dropdowns on cards have been updated dvt101/update-cards

- superset-frontend/src/components/DvtNavbar/dvt-navbar.module.tsx
- superset-frontend/src/components/DvtNavbar/index.tsx
- superset-frontend/src/components/DvtSidebar/dvt-sidebar.module.tsx
- superset-frontend/src/components/DvtSidebar/index.tsx
- superset-frontend/src/views/dvt-layout.tsx
> fix: DVT-88

- superset-frontend/packages/superset-ui-core/src/style/index.tsx
- superset-frontend/src/dvt-modal/dvt-modal.module.tsx
- superset-frontend/src/dvt-modal/index.tsx
- superset-frontend/src/dvt-redux/dvt-modalReducer.ts
- superset-frontend/src/views/dvt-layout.tsx
- superset-frontend/src/views/dvt-store.ts
> feat: DVT-80

- superset-frontend/src/components/DvtCard/index.tsx
- superset-frontend/src/components/DvtDropdown/index.tsx
- superset-frontend/src/components/DvtTitleCardList/index.tsx
- superset-frontend/src/dvt-modal/body/dashboard-edit/dashboard-edit.module.tsx
- superset-frontend/src/dvt-modal/body/dashboard-edit/index.tsx
- superset-frontend/src/dvt-modal/dvt-modal.module.tsx
- superset-frontend/src/dvt-modal/index.tsx
- superset-frontend/src/dvt-redux/dvt-modalReducer.ts
- superset-frontend/src/pages/DvtHome/index.tsx
- superset-frontend/src/views/dvt-store.ts
> feat: DVT-103

- superset-frontend/src/pages/DvtHome/index.tsx
> feat: fixed dvt102

- superset-frontend/src/components/DvtDropdown/dvt-dropdown.module.tsx
- superset-frontend/src/components/DvtDropdown/dvt-dropdown.stories.tsx
- superset-frontend/src/components/DvtDropdown/index.tsx
- superset-frontend/src/components/DvtNavbar/dvt-navbar.module.tsx
- superset-frontend/src/components/DvtNavbar/index.tsx
- superset-frontend/src/views/dvt-layout.tsx
> fix: dvt-dropdown changes and new languages add for navbar fixed

- superset-frontend/src/components/DvtInputSelect/dvt-input-select.module.tsx
- superset-frontend/src/components/DvtInputSelect/dvt-input-select.stories.tsx
- superset-frontend/src/components/DvtInputSelect/index.tsx
> feat: DVT-106

- superset-frontend/src/components/DvtSelectButton/dvt-select-button.module.tsx
- superset-frontend/src/components/DvtSelectButton/dvt-select-button.stories.tsx
- superset-frontend/src/components/DvtSelectButton/index.tsx
> feat: DVT-131

- superset-frontend/src/components/DvtCheckbox/dvt-checkbox.module.tsx
- superset-frontend/src/components/DvtCheckbox/dvt-checkbox.stories.tsx
- superset-frontend/src/components/DvtCheckbox/index.tsx
> feat: DEV-132

- superset-frontend/src/dvt-modal/body/delete-modal/delete-modal.module.tsx
- superset-frontend/src/dvt-modal/body/delete-modal/index.tsx
- superset-frontend/src/dvt-modal/dvt-modal.module.tsx
- superset-frontend/src/dvt-modal/index.tsx
- superset-frontend/src/dvt-redux/dvt-homeReducer.ts
- superset-frontend/src/pages/DvtHome/index.tsx
- superset-frontend/src/views/dvt-store.ts
> feat: DVT-104

- superset-frontend/src/components/DvtSidebar/dvtSidebarData.ts
- superset-frontend/src/components/DvtSidebar/index.tsx
- superset-frontend/src/dvt-redux/dvt-sidebarReducer.ts
- superset-frontend/src/pages/DvtSqllab/index.tsx
- superset-frontend/src/views/dvt-routes.tsx
> fix: try new page sqlhub
